#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 104
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 47
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 14
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 2

enum ts_symbol_identifiers {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  anon_sym_LT = 5,
  anon_sym_SLASH_GT = 6,
  anon_sym_LT_SLASH = 7,
  anon_sym_EQ = 8,
  sym_attribute_name = 9,
  aux_sym_attribute_value_token1 = 10,
  sym_entity = 11,
  anon_sym_SQUOTE = 12,
  anon_sym_DQUOTE = 13,
  sym_escaped_echo_statement = 14,
  sym_unescaped_echo_statement = 15,
  sym__single_quoted_attribute_value_fragment = 16,
  sym__double_quoted_attribute_value_fragment = 17,
  sym__start_tag_name = 18,
  sym__script_start_tag_name = 19,
  sym__style_start_tag_name = 20,
  sym__end_tag_name = 21,
  sym_erroneous_end_tag_name = 22,
  sym__implicit_end_tag = 23,
  sym_raw_text = 24,
  sym_text = 25,
  sym_comment = 26,
  sym_document = 27,
  sym_doctype = 28,
  sym__node = 29,
  sym_echo_statement = 30,
  sym_element = 31,
  sym_script_element = 32,
  sym_style_element = 33,
  sym_start_tag = 34,
  sym_script_start_tag = 35,
  sym_style_start_tag = 36,
  sym_self_closing_tag = 37,
  sym_end_tag = 38,
  sym_erroneous_end_tag = 39,
  sym_attribute = 40,
  sym_attribute_value = 41,
  sym_quoted_attribute_value = 42,
  aux_sym__single_quotes_attribute_value = 43,
  aux_sym__double_quotes_attribute_value = 44,
  aux_sym_document_repeat1 = 45,
  aux_sym_start_tag_repeat1 = 46,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [aux_sym_attribute_value_token1] = "attribute_value_token1",
  [sym_entity] = "entity",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_DQUOTE] = "\"",
  [sym_escaped_echo_statement] = "escaped_echo_statement",
  [sym_unescaped_echo_statement] = "unescaped_echo_statement",
  [sym__single_quoted_attribute_value_fragment] = "_single_quoted_attribute_value_fragment",
  [sym__double_quoted_attribute_value_fragment] = "_double_quoted_attribute_value_fragment",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_text] = "text",
  [sym_comment] = "comment",
  [sym_document] = "document",
  [sym_doctype] = "doctype",
  [sym__node] = "_node",
  [sym_echo_statement] = "echo_statement",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_attribute_value] = "attribute_value",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [aux_sym__single_quotes_attribute_value] = "_single_quotes_attribute_value",
  [aux_sym__double_quotes_attribute_value] = "_double_quotes_attribute_value",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [aux_sym_attribute_value_token1] = aux_sym_attribute_value_token1,
  [sym_entity] = sym_entity,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_escaped_echo_statement] = sym_escaped_echo_statement,
  [sym_unescaped_echo_statement] = sym_unescaped_echo_statement,
  [sym__single_quoted_attribute_value_fragment] = sym__single_quoted_attribute_value_fragment,
  [sym__double_quoted_attribute_value_fragment] = sym__double_quoted_attribute_value_fragment,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_text] = sym_text,
  [sym_comment] = sym_comment,
  [sym_document] = sym_document,
  [sym_doctype] = sym_doctype,
  [sym__node] = sym__node,
  [sym_echo_statement] = sym_echo_statement,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_attribute_value] = sym_attribute_value,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [aux_sym__single_quotes_attribute_value] = aux_sym__single_quotes_attribute_value,
  [aux_sym__double_quotes_attribute_value] = aux_sym__double_quotes_attribute_value,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_attribute_value_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_entity] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_escaped_echo_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_unescaped_echo_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__single_quoted_attribute_value_fragment] = {
    .visible = false,
    .named = true,
  },
  [sym__double_quoted_attribute_value_fragment] = {
    .visible = false,
    .named = true,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_echo_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__single_quotes_attribute_value] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__double_quotes_attribute_value] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = sym_attribute_value,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__single_quotes_attribute_value, 2,
    aux_sym__single_quotes_attribute_value,
    sym_attribute_value,
  aux_sym__double_quotes_attribute_value, 2,
    aux_sym__double_quotes_attribute_value,
    sym_attribute_value,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 10,
  [16] = 16,
  [17] = 16,
  [18] = 18,
  [19] = 12,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 18,
  [24] = 9,
  [25] = 11,
  [26] = 26,
  [27] = 13,
  [28] = 22,
  [29] = 21,
  [30] = 30,
  [31] = 31,
  [32] = 14,
  [33] = 33,
  [34] = 33,
  [35] = 31,
  [36] = 30,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 39,
  [41] = 37,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 38,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 49,
  [52] = 52,
  [53] = 44,
  [54] = 54,
  [55] = 55,
  [56] = 50,
  [57] = 52,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 62,
  [64] = 64,
  [65] = 65,
  [66] = 45,
  [67] = 59,
  [68] = 68,
  [69] = 68,
  [70] = 65,
  [71] = 71,
  [72] = 72,
  [73] = 71,
  [74] = 74,
  [75] = 65,
  [76] = 64,
  [77] = 60,
  [78] = 58,
  [79] = 61,
  [80] = 65,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 72,
  [86] = 86,
  [87] = 87,
  [88] = 82,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 92,
  [94] = 90,
  [95] = 95,
  [96] = 96,
  [97] = 89,
  [98] = 98,
  [99] = 96,
  [100] = 91,
  [101] = 101,
  [102] = 101,
  [103] = 98,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(14);
      ADVANCE_MAP(
        '"', 67,
        '&', 2,
        '\'', 66,
        '/', 4,
        '<', 20,
        '=', 23,
        '>', 18,
        'D', 7,
        'd', 7,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(67);
      if (lookahead == '\'') ADVANCE(66);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(25);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '=') ADVANCE(23);
      if (lookahead == '>') ADVANCE(18);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(24);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(21);
      END_STATE();
    case 5:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(9);
      END_STATE();
    case 6:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 7:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(5);
      END_STATE();
    case 8:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 11:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(8);
      END_STATE();
    case 12:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(17);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(36);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(15);
      if (lookahead == '/') ADVANCE(22);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_entity);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(34);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(27);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(37);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(38);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(26);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 3},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 3},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 3},
  [14] = {.lex_state = 0, .external_lex_state = 3},
  [15] = {.lex_state = 0, .external_lex_state = 2},
  [16] = {.lex_state = 0, .external_lex_state = 2},
  [17] = {.lex_state = 0, .external_lex_state = 3},
  [18] = {.lex_state = 0, .external_lex_state = 3},
  [19] = {.lex_state = 0, .external_lex_state = 3},
  [20] = {.lex_state = 0, .external_lex_state = 3},
  [21] = {.lex_state = 0, .external_lex_state = 2},
  [22] = {.lex_state = 1, .external_lex_state = 4},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 3},
  [25] = {.lex_state = 0, .external_lex_state = 3},
  [26] = {.lex_state = 0, .external_lex_state = 3},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 1, .external_lex_state = 4},
  [29] = {.lex_state = 0, .external_lex_state = 3},
  [30] = {.lex_state = 0, .external_lex_state = 3},
  [31] = {.lex_state = 0, .external_lex_state = 3},
  [32] = {.lex_state = 0, .external_lex_state = 2},
  [33] = {.lex_state = 0, .external_lex_state = 3},
  [34] = {.lex_state = 0, .external_lex_state = 2},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 0, .external_lex_state = 2},
  [37] = {.lex_state = 3, .external_lex_state = 5},
  [38] = {.lex_state = 3, .external_lex_state = 5},
  [39] = {.lex_state = 3, .external_lex_state = 5},
  [40] = {.lex_state = 3, .external_lex_state = 5},
  [41] = {.lex_state = 3, .external_lex_state = 5},
  [42] = {.lex_state = 3, .external_lex_state = 4},
  [43] = {.lex_state = 3, .external_lex_state = 4},
  [44] = {.lex_state = 0, .external_lex_state = 6},
  [45] = {.lex_state = 3, .external_lex_state = 5},
  [46] = {.lex_state = 3, .external_lex_state = 4},
  [47] = {.lex_state = 3, .external_lex_state = 4},
  [48] = {.lex_state = 3, .external_lex_state = 4},
  [49] = {.lex_state = 0, .external_lex_state = 7},
  [50] = {.lex_state = 0, .external_lex_state = 6},
  [51] = {.lex_state = 0, .external_lex_state = 7},
  [52] = {.lex_state = 0, .external_lex_state = 7},
  [53] = {.lex_state = 0, .external_lex_state = 6},
  [54] = {.lex_state = 0, .external_lex_state = 7},
  [55] = {.lex_state = 0, .external_lex_state = 6},
  [56] = {.lex_state = 0, .external_lex_state = 6},
  [57] = {.lex_state = 0, .external_lex_state = 7},
  [58] = {.lex_state = 3, .external_lex_state = 5},
  [59] = {.lex_state = 0, .external_lex_state = 8},
  [60] = {.lex_state = 3, .external_lex_state = 5},
  [61] = {.lex_state = 3, .external_lex_state = 5},
  [62] = {.lex_state = 0, .external_lex_state = 9},
  [63] = {.lex_state = 0, .external_lex_state = 9},
  [64] = {.lex_state = 3, .external_lex_state = 5},
  [65] = {.lex_state = 3, .external_lex_state = 5},
  [66] = {.lex_state = 3, .external_lex_state = 4},
  [67] = {.lex_state = 0, .external_lex_state = 8},
  [68] = {.lex_state = 0, .external_lex_state = 8},
  [69] = {.lex_state = 0, .external_lex_state = 8},
  [70] = {.lex_state = 0, .external_lex_state = 6},
  [71] = {.lex_state = 0, .external_lex_state = 4},
  [72] = {.lex_state = 0, .external_lex_state = 10},
  [73] = {.lex_state = 0, .external_lex_state = 4},
  [74] = {.lex_state = 0, .external_lex_state = 8},
  [75] = {.lex_state = 3, .external_lex_state = 4},
  [76] = {.lex_state = 3, .external_lex_state = 4},
  [77] = {.lex_state = 3, .external_lex_state = 4},
  [78] = {.lex_state = 3, .external_lex_state = 4},
  [79] = {.lex_state = 3, .external_lex_state = 4},
  [80] = {.lex_state = 0, .external_lex_state = 7},
  [81] = {.lex_state = 0, .external_lex_state = 6},
  [82] = {.lex_state = 0, .external_lex_state = 4},
  [83] = {.lex_state = 0, .external_lex_state = 7},
  [84] = {.lex_state = 0, .external_lex_state = 8},
  [85] = {.lex_state = 0, .external_lex_state = 10},
  [86] = {.lex_state = 0, .external_lex_state = 8},
  [87] = {.lex_state = 0, .external_lex_state = 8},
  [88] = {.lex_state = 0, .external_lex_state = 4},
  [89] = {.lex_state = 0, .external_lex_state = 4},
  [90] = {.lex_state = 0, .external_lex_state = 4},
  [91] = {.lex_state = 12, .external_lex_state = 4},
  [92] = {.lex_state = 0, .external_lex_state = 4},
  [93] = {.lex_state = 0, .external_lex_state = 4},
  [94] = {.lex_state = 0, .external_lex_state = 4},
  [95] = {.lex_state = 0, .external_lex_state = 4},
  [96] = {.lex_state = 0, .external_lex_state = 11},
  [97] = {.lex_state = 0, .external_lex_state = 4},
  [98] = {.lex_state = 0, .external_lex_state = 4},
  [99] = {.lex_state = 0, .external_lex_state = 11},
  [100] = {.lex_state = 12, .external_lex_state = 4},
  [101] = {.lex_state = 0, .external_lex_state = 12},
  [102] = {.lex_state = 0, .external_lex_state = 12},
  [103] = {.lex_state = 0, .external_lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_entity] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_escaped_echo_statement] = ACTIONS(3),
    [sym_unescaped_echo_statement] = ACTIONS(3),
    [sym__single_quoted_attribute_value_fragment] = ACTIONS(1),
    [sym__double_quoted_attribute_value_fragment] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_document] = STATE(95),
    [sym_doctype] = STATE(7),
    [sym__node] = STATE(7),
    [sym_element] = STATE(7),
    [sym_script_element] = STATE(7),
    [sym_style_element] = STATE(7),
    [sym_start_tag] = STATE(5),
    [sym_script_start_tag] = STATE(67),
    [sym_style_start_tag] = STATE(68),
    [sym_self_closing_tag] = STATE(9),
    [sym_erroneous_end_tag] = STATE(7),
    [aux_sym_document_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_entity] = ACTIONS(13),
    [sym_escaped_echo_statement] = ACTIONS(3),
    [sym_unescaped_echo_statement] = ACTIONS(3),
    [sym_text] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    ACTIONS(23), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(24), 1,
      sym_self_closing_tag,
    STATE(33), 1,
      sym_end_tag,
    STATE(59), 1,
      sym_script_start_tag,
    STATE(69), 1,
      sym_style_start_tag,
    ACTIONS(21), 2,
      sym_text,
      sym_entity,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    STATE(8), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [46] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(27), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(24), 1,
      sym_self_closing_tag,
    STATE(34), 1,
      sym_end_tag,
    STATE(59), 1,
      sym_script_start_tag,
    STATE(69), 1,
      sym_style_start_tag,
    ACTIONS(21), 2,
      sym_text,
      sym_entity,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    STATE(8), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [92] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    ACTIONS(31), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(17), 1,
      sym_end_tag,
    STATE(24), 1,
      sym_self_closing_tag,
    STATE(59), 1,
      sym_script_start_tag,
    STATE(69), 1,
      sym_style_start_tag,
    ACTIONS(29), 2,
      sym_text,
      sym_entity,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    STATE(2), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [138] = 12,
    ACTIONS(15), 1,
      anon_sym_LT_BANG,
    ACTIONS(17), 1,
      anon_sym_LT,
    ACTIONS(25), 1,
      anon_sym_LT_SLASH,
    ACTIONS(35), 1,
      sym__implicit_end_tag,
    STATE(4), 1,
      sym_start_tag,
    STATE(16), 1,
      sym_end_tag,
    STATE(24), 1,
      sym_self_closing_tag,
    STATE(59), 1,
      sym_script_start_tag,
    STATE(69), 1,
      sym_style_start_tag,
    ACTIONS(33), 2,
      sym_text,
      sym_entity,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    STATE(3), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [184] = 11,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(39), 1,
      anon_sym_LT_BANG,
    ACTIONS(42), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_LT_SLASH,
    STATE(5), 1,
      sym_start_tag,
    STATE(9), 1,
      sym_self_closing_tag,
    STATE(67), 1,
      sym_script_start_tag,
    STATE(68), 1,
      sym_style_start_tag,
    ACTIONS(48), 2,
      sym_text,
      sym_entity,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    STATE(6), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [227] = 11,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    STATE(5), 1,
      sym_start_tag,
    STATE(9), 1,
      sym_self_closing_tag,
    STATE(67), 1,
      sym_script_start_tag,
    STATE(68), 1,
      sym_style_start_tag,
    ACTIONS(53), 2,
      sym_text,
      sym_entity,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    STATE(6), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [270] = 11,
    ACTIONS(37), 1,
      sym__implicit_end_tag,
    ACTIONS(55), 1,
      anon_sym_LT_BANG,
    ACTIONS(58), 1,
      anon_sym_LT,
    ACTIONS(61), 1,
      anon_sym_LT_SLASH,
    STATE(4), 1,
      sym_start_tag,
    STATE(24), 1,
      sym_self_closing_tag,
    STATE(59), 1,
      sym_script_start_tag,
    STATE(69), 1,
      sym_style_start_tag,
    ACTIONS(64), 2,
      sym_text,
      sym_entity,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    STATE(8), 7,
      sym_doctype,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [313] = 3,
    ACTIONS(69), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(67), 5,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [329] = 3,
    ACTIONS(73), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(71), 5,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [345] = 3,
    ACTIONS(77), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(75), 5,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [361] = 3,
    ACTIONS(81), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(79), 5,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [377] = 3,
    ACTIONS(85), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(83), 5,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [393] = 3,
    ACTIONS(89), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(87), 5,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [409] = 3,
    ACTIONS(73), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(71), 5,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [425] = 3,
    ACTIONS(93), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(91), 5,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [441] = 3,
    ACTIONS(93), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(91), 5,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [457] = 3,
    ACTIONS(97), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(95), 5,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [473] = 3,
    ACTIONS(81), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(79), 5,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [489] = 3,
    ACTIONS(101), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(99), 5,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [505] = 3,
    ACTIONS(105), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(103), 5,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [521] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(107), 1,
      aux_sym_attribute_value_token1,
    ACTIONS(109), 1,
      anon_sym_SQUOTE,
    ACTIONS(111), 1,
      anon_sym_DQUOTE,
    STATE(76), 1,
      sym_echo_statement,
    ACTIONS(113), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(77), 2,
      sym_attribute_value,
      sym_quoted_attribute_value,
  [545] = 3,
    ACTIONS(97), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(95), 5,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [561] = 3,
    ACTIONS(69), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(67), 5,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [577] = 3,
    ACTIONS(77), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(75), 5,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [593] = 3,
    ACTIONS(117), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(115), 5,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [609] = 3,
    ACTIONS(85), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(83), 5,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [625] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(119), 1,
      aux_sym_attribute_value_token1,
    ACTIONS(121), 1,
      anon_sym_SQUOTE,
    ACTIONS(123), 1,
      anon_sym_DQUOTE,
    STATE(64), 1,
      sym_echo_statement,
    ACTIONS(125), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(60), 2,
      sym_attribute_value,
      sym_quoted_attribute_value,
  [649] = 3,
    ACTIONS(105), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(103), 5,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [665] = 3,
    ACTIONS(129), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(127), 5,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [681] = 3,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(131), 5,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [697] = 3,
    ACTIONS(89), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(87), 5,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [713] = 3,
    ACTIONS(137), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(135), 5,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [729] = 3,
    ACTIONS(137), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(135), 5,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [745] = 3,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(131), 5,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [761] = 3,
    ACTIONS(129), 1,
      anon_sym_LT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(127), 5,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [777] = 5,
    ACTIONS(139), 1,
      anon_sym_GT,
    ACTIONS(141), 1,
      anon_sym_SLASH_GT,
    ACTIONS(143), 1,
      sym_attribute_name,
    STATE(38), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [796] = 4,
    ACTIONS(147), 1,
      sym_attribute_name,
    ACTIONS(145), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(38), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [813] = 5,
    ACTIONS(143), 1,
      sym_attribute_name,
    ACTIONS(150), 1,
      anon_sym_GT,
    ACTIONS(152), 1,
      anon_sym_SLASH_GT,
    STATE(41), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [832] = 5,
    ACTIONS(143), 1,
      sym_attribute_name,
    ACTIONS(150), 1,
      anon_sym_GT,
    ACTIONS(154), 1,
      anon_sym_SLASH_GT,
    STATE(37), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [851] = 5,
    ACTIONS(139), 1,
      anon_sym_GT,
    ACTIONS(143), 1,
      sym_attribute_name,
    ACTIONS(156), 1,
      anon_sym_SLASH_GT,
    STATE(38), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [870] = 4,
    ACTIONS(158), 1,
      anon_sym_GT,
    ACTIONS(160), 1,
      sym_attribute_name,
    STATE(46), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [886] = 4,
    ACTIONS(160), 1,
      sym_attribute_name,
    ACTIONS(162), 1,
      anon_sym_GT,
    STATE(46), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [902] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_DQUOTE,
    ACTIONS(168), 1,
      sym__double_quoted_attribute_value_fragment,
    STATE(55), 1,
      aux_sym__double_quotes_attribute_value,
    STATE(81), 1,
      sym_echo_statement,
    ACTIONS(166), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
  [922] = 3,
    ACTIONS(172), 1,
      anon_sym_EQ,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(170), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [936] = 4,
    ACTIONS(145), 1,
      anon_sym_GT,
    ACTIONS(174), 1,
      sym_attribute_name,
    STATE(46), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [952] = 4,
    ACTIONS(160), 1,
      sym_attribute_name,
    ACTIONS(177), 1,
      anon_sym_GT,
    STATE(43), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [968] = 4,
    ACTIONS(160), 1,
      sym_attribute_name,
    ACTIONS(179), 1,
      anon_sym_GT,
    STATE(42), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [984] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_SQUOTE,
    ACTIONS(185), 1,
      sym__single_quoted_attribute_value_fragment,
    STATE(52), 1,
      aux_sym__single_quotes_attribute_value,
    STATE(83), 1,
      sym_echo_statement,
    ACTIONS(183), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
  [1004] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      sym__double_quoted_attribute_value_fragment,
    ACTIONS(181), 1,
      anon_sym_DQUOTE,
    STATE(53), 1,
      aux_sym__double_quotes_attribute_value,
    STATE(81), 1,
      sym_echo_statement,
    ACTIONS(166), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
  [1024] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym__single_quoted_attribute_value_fragment,
    ACTIONS(187), 1,
      anon_sym_SQUOTE,
    STATE(57), 1,
      aux_sym__single_quotes_attribute_value,
    STATE(83), 1,
      sym_echo_statement,
    ACTIONS(183), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
  [1044] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      sym__single_quoted_attribute_value_fragment,
    ACTIONS(189), 1,
      anon_sym_SQUOTE,
    STATE(54), 1,
      aux_sym__single_quotes_attribute_value,
    STATE(83), 1,
      sym_echo_statement,
    ACTIONS(183), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
  [1064] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      sym__double_quoted_attribute_value_fragment,
    ACTIONS(189), 1,
      anon_sym_DQUOTE,
    STATE(55), 1,
      aux_sym__double_quotes_attribute_value,
    STATE(81), 1,
      sym_echo_statement,
    ACTIONS(166), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
  [1084] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_SQUOTE,
    ACTIONS(196), 1,
      sym__single_quoted_attribute_value_fragment,
    STATE(54), 1,
      aux_sym__single_quotes_attribute_value,
    STATE(83), 1,
      sym_echo_statement,
    ACTIONS(193), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
  [1104] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_DQUOTE,
    ACTIONS(204), 1,
      sym__double_quoted_attribute_value_fragment,
    STATE(55), 1,
      aux_sym__double_quotes_attribute_value,
    STATE(81), 1,
      sym_echo_statement,
    ACTIONS(201), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
  [1124] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(168), 1,
      sym__double_quoted_attribute_value_fragment,
    ACTIONS(187), 1,
      anon_sym_DQUOTE,
    STATE(44), 1,
      aux_sym__double_quotes_attribute_value,
    STATE(81), 1,
      sym_echo_statement,
    ACTIONS(166), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
  [1144] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(164), 1,
      anon_sym_SQUOTE,
    ACTIONS(185), 1,
      sym__single_quoted_attribute_value_fragment,
    STATE(54), 1,
      aux_sym__single_quotes_attribute_value,
    STATE(83), 1,
      sym_echo_statement,
    ACTIONS(183), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
  [1164] = 2,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(207), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1175] = 4,
    ACTIONS(209), 1,
      anon_sym_LT_SLASH,
    ACTIONS(211), 1,
      sym_raw_text,
    STATE(29), 1,
      sym_end_tag,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1190] = 2,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(213), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1201] = 2,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(215), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1212] = 4,
    ACTIONS(217), 1,
      sym__start_tag_name,
    ACTIONS(219), 1,
      sym__script_start_tag_name,
    ACTIONS(221), 1,
      sym__style_start_tag_name,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1227] = 4,
    ACTIONS(219), 1,
      sym__script_start_tag_name,
    ACTIONS(221), 1,
      sym__style_start_tag_name,
    ACTIONS(223), 1,
      sym__start_tag_name,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1242] = 2,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(225), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1253] = 2,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
    ACTIONS(227), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1264] = 3,
    ACTIONS(229), 1,
      anon_sym_EQ,
    ACTIONS(170), 2,
      anon_sym_GT,
      sym_attribute_name,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1277] = 4,
    ACTIONS(231), 1,
      anon_sym_LT_SLASH,
    ACTIONS(233), 1,
      sym_raw_text,
    STATE(21), 1,
      sym_end_tag,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1292] = 4,
    ACTIONS(231), 1,
      anon_sym_LT_SLASH,
    ACTIONS(235), 1,
      sym_raw_text,
    STATE(23), 1,
      sym_end_tag,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1307] = 4,
    ACTIONS(209), 1,
      anon_sym_LT_SLASH,
    ACTIONS(237), 1,
      sym_raw_text,
    STATE(18), 1,
      sym_end_tag,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1322] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 4,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym__double_quoted_attribute_value_fragment,
      anon_sym_DQUOTE,
  [1332] = 3,
    ACTIONS(209), 1,
      anon_sym_LT_SLASH,
    STATE(30), 1,
      sym_end_tag,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1344] = 3,
    ACTIONS(239), 1,
      sym__end_tag_name,
    ACTIONS(241), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1356] = 3,
    ACTIONS(231), 1,
      anon_sym_LT_SLASH,
    STATE(36), 1,
      sym_end_tag,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1368] = 2,
    ACTIONS(243), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1378] = 2,
    ACTIONS(227), 2,
      anon_sym_GT,
      sym_attribute_name,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1388] = 2,
    ACTIONS(225), 2,
      anon_sym_GT,
      sym_attribute_name,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1398] = 2,
    ACTIONS(213), 2,
      anon_sym_GT,
      sym_attribute_name,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1408] = 2,
    ACTIONS(207), 2,
      anon_sym_GT,
      sym_attribute_name,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1418] = 2,
    ACTIONS(215), 2,
      anon_sym_GT,
      sym_attribute_name,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1428] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(227), 4,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym__single_quoted_attribute_value_fragment,
      anon_sym_SQUOTE,
  [1438] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 4,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym__double_quoted_attribute_value_fragment,
      anon_sym_DQUOTE,
  [1448] = 3,
    ACTIONS(231), 1,
      anon_sym_LT_SLASH,
    STATE(35), 1,
      sym_end_tag,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1460] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 4,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym__single_quoted_attribute_value_fragment,
      anon_sym_SQUOTE,
  [1470] = 2,
    ACTIONS(249), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1480] = 3,
    ACTIONS(241), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(251), 1,
      sym__end_tag_name,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1492] = 2,
    ACTIONS(253), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1502] = 2,
    ACTIONS(255), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1512] = 3,
    ACTIONS(209), 1,
      anon_sym_LT_SLASH,
    STATE(31), 1,
      sym_end_tag,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1524] = 2,
    ACTIONS(257), 1,
      anon_sym_GT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1533] = 2,
    ACTIONS(259), 1,
      anon_sym_GT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1542] = 2,
    ACTIONS(261), 1,
      aux_sym_doctype_token1,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1551] = 2,
    ACTIONS(263), 1,
      anon_sym_GT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1560] = 2,
    ACTIONS(265), 1,
      anon_sym_GT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1569] = 2,
    ACTIONS(267), 1,
      anon_sym_GT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1578] = 2,
    ACTIONS(269), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1587] = 2,
    ACTIONS(271), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1596] = 2,
    ACTIONS(273), 1,
      anon_sym_GT,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1605] = 2,
    ACTIONS(275), 1,
      sym__doctype,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1614] = 2,
    ACTIONS(241), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1623] = 2,
    ACTIONS(277), 1,
      aux_sym_doctype_token1,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1632] = 2,
    ACTIONS(251), 1,
      sym__end_tag_name,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1641] = 2,
    ACTIONS(239), 1,
      sym__end_tag_name,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
  [1650] = 2,
    ACTIONS(279), 1,
      sym__doctype,
    ACTIONS(3), 3,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
      sym_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 46,
  [SMALL_STATE(4)] = 92,
  [SMALL_STATE(5)] = 138,
  [SMALL_STATE(6)] = 184,
  [SMALL_STATE(7)] = 227,
  [SMALL_STATE(8)] = 270,
  [SMALL_STATE(9)] = 313,
  [SMALL_STATE(10)] = 329,
  [SMALL_STATE(11)] = 345,
  [SMALL_STATE(12)] = 361,
  [SMALL_STATE(13)] = 377,
  [SMALL_STATE(14)] = 393,
  [SMALL_STATE(15)] = 409,
  [SMALL_STATE(16)] = 425,
  [SMALL_STATE(17)] = 441,
  [SMALL_STATE(18)] = 457,
  [SMALL_STATE(19)] = 473,
  [SMALL_STATE(20)] = 489,
  [SMALL_STATE(21)] = 505,
  [SMALL_STATE(22)] = 521,
  [SMALL_STATE(23)] = 545,
  [SMALL_STATE(24)] = 561,
  [SMALL_STATE(25)] = 577,
  [SMALL_STATE(26)] = 593,
  [SMALL_STATE(27)] = 609,
  [SMALL_STATE(28)] = 625,
  [SMALL_STATE(29)] = 649,
  [SMALL_STATE(30)] = 665,
  [SMALL_STATE(31)] = 681,
  [SMALL_STATE(32)] = 697,
  [SMALL_STATE(33)] = 713,
  [SMALL_STATE(34)] = 729,
  [SMALL_STATE(35)] = 745,
  [SMALL_STATE(36)] = 761,
  [SMALL_STATE(37)] = 777,
  [SMALL_STATE(38)] = 796,
  [SMALL_STATE(39)] = 813,
  [SMALL_STATE(40)] = 832,
  [SMALL_STATE(41)] = 851,
  [SMALL_STATE(42)] = 870,
  [SMALL_STATE(43)] = 886,
  [SMALL_STATE(44)] = 902,
  [SMALL_STATE(45)] = 922,
  [SMALL_STATE(46)] = 936,
  [SMALL_STATE(47)] = 952,
  [SMALL_STATE(48)] = 968,
  [SMALL_STATE(49)] = 984,
  [SMALL_STATE(50)] = 1004,
  [SMALL_STATE(51)] = 1024,
  [SMALL_STATE(52)] = 1044,
  [SMALL_STATE(53)] = 1064,
  [SMALL_STATE(54)] = 1084,
  [SMALL_STATE(55)] = 1104,
  [SMALL_STATE(56)] = 1124,
  [SMALL_STATE(57)] = 1144,
  [SMALL_STATE(58)] = 1164,
  [SMALL_STATE(59)] = 1175,
  [SMALL_STATE(60)] = 1190,
  [SMALL_STATE(61)] = 1201,
  [SMALL_STATE(62)] = 1212,
  [SMALL_STATE(63)] = 1227,
  [SMALL_STATE(64)] = 1242,
  [SMALL_STATE(65)] = 1253,
  [SMALL_STATE(66)] = 1264,
  [SMALL_STATE(67)] = 1277,
  [SMALL_STATE(68)] = 1292,
  [SMALL_STATE(69)] = 1307,
  [SMALL_STATE(70)] = 1322,
  [SMALL_STATE(71)] = 1332,
  [SMALL_STATE(72)] = 1344,
  [SMALL_STATE(73)] = 1356,
  [SMALL_STATE(74)] = 1368,
  [SMALL_STATE(75)] = 1378,
  [SMALL_STATE(76)] = 1388,
  [SMALL_STATE(77)] = 1398,
  [SMALL_STATE(78)] = 1408,
  [SMALL_STATE(79)] = 1418,
  [SMALL_STATE(80)] = 1428,
  [SMALL_STATE(81)] = 1438,
  [SMALL_STATE(82)] = 1448,
  [SMALL_STATE(83)] = 1460,
  [SMALL_STATE(84)] = 1470,
  [SMALL_STATE(85)] = 1480,
  [SMALL_STATE(86)] = 1492,
  [SMALL_STATE(87)] = 1502,
  [SMALL_STATE(88)] = 1512,
  [SMALL_STATE(89)] = 1524,
  [SMALL_STATE(90)] = 1533,
  [SMALL_STATE(91)] = 1542,
  [SMALL_STATE(92)] = 1551,
  [SMALL_STATE(93)] = 1560,
  [SMALL_STATE(94)] = 1569,
  [SMALL_STATE(95)] = 1578,
  [SMALL_STATE(96)] = 1587,
  [SMALL_STATE(97)] = 1596,
  [SMALL_STATE(98)] = 1605,
  [SMALL_STATE(99)] = 1614,
  [SMALL_STATE(100)] = 1623,
  [SMALL_STATE(101)] = 1632,
  [SMALL_STATE(102)] = 1641,
  [SMALL_STATE(103)] = 1650,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(98),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(96),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(99),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [147] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [174] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__single_quotes_attribute_value, 2, 0, 0),
  [193] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__single_quotes_attribute_value, 2, 0, 0), SHIFT_REPEAT(80),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__single_quotes_attribute_value, 2, 0, 0), SHIFT_REPEAT(83),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__double_quotes_attribute_value, 2, 0, 0),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__double_quotes_attribute_value, 2, 0, 0), SHIFT_REPEAT(70),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__double_quotes_attribute_value, 2, 0, 0), SHIFT_REPEAT(81),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 1),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 1, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_statement, 1, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__double_quotes_attribute_value, 1, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__single_quotes_attribute_value, 1, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3, 0, 0),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [269] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_escaped_echo_statement = 0,
  ts_external_token_unescaped_echo_statement = 1,
  ts_external_token__single_quoted_attribute_value_fragment = 2,
  ts_external_token__double_quoted_attribute_value_fragment = 3,
  ts_external_token__start_tag_name = 4,
  ts_external_token__script_start_tag_name = 5,
  ts_external_token__style_start_tag_name = 6,
  ts_external_token__end_tag_name = 7,
  ts_external_token_erroneous_end_tag_name = 8,
  ts_external_token_SLASH_GT = 9,
  ts_external_token__implicit_end_tag = 10,
  ts_external_token_raw_text = 11,
  ts_external_token_text = 12,
  ts_external_token_comment = 13,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_escaped_echo_statement] = sym_escaped_echo_statement,
  [ts_external_token_unescaped_echo_statement] = sym_unescaped_echo_statement,
  [ts_external_token__single_quoted_attribute_value_fragment] = sym__single_quoted_attribute_value_fragment,
  [ts_external_token__double_quoted_attribute_value_fragment] = sym__double_quoted_attribute_value_fragment,
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_text] = sym_text,
  [ts_external_token_comment] = sym_comment,
};

static const bool ts_external_scanner_states[13][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_escaped_echo_statement] = true,
    [ts_external_token_unescaped_echo_statement] = true,
    [ts_external_token__single_quoted_attribute_value_fragment] = true,
    [ts_external_token__double_quoted_attribute_value_fragment] = true,
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_text] = true,
    [ts_external_token_comment] = true,
  },
  [2] = {
    [ts_external_token_escaped_echo_statement] = true,
    [ts_external_token_unescaped_echo_statement] = true,
    [ts_external_token_text] = true,
    [ts_external_token_comment] = true,
  },
  [3] = {
    [ts_external_token_escaped_echo_statement] = true,
    [ts_external_token_unescaped_echo_statement] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_text] = true,
    [ts_external_token_comment] = true,
  },
  [4] = {
    [ts_external_token_escaped_echo_statement] = true,
    [ts_external_token_unescaped_echo_statement] = true,
    [ts_external_token_comment] = true,
  },
  [5] = {
    [ts_external_token_escaped_echo_statement] = true,
    [ts_external_token_unescaped_echo_statement] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [6] = {
    [ts_external_token_escaped_echo_statement] = true,
    [ts_external_token_unescaped_echo_statement] = true,
    [ts_external_token__double_quoted_attribute_value_fragment] = true,
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token_escaped_echo_statement] = true,
    [ts_external_token_unescaped_echo_statement] = true,
    [ts_external_token__single_quoted_attribute_value_fragment] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token_escaped_echo_statement] = true,
    [ts_external_token_unescaped_echo_statement] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [9] = {
    [ts_external_token_escaped_echo_statement] = true,
    [ts_external_token_unescaped_echo_statement] = true,
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [10] = {
    [ts_external_token_escaped_echo_statement] = true,
    [ts_external_token_unescaped_echo_statement] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [11] = {
    [ts_external_token_escaped_echo_statement] = true,
    [ts_external_token_unescaped_echo_statement] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [12] = {
    [ts_external_token_escaped_echo_statement] = true,
    [ts_external_token_unescaped_echo_statement] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_blade_external_scanner_create(void);
void tree_sitter_blade_external_scanner_destroy(void *);
bool tree_sitter_blade_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_blade_external_scanner_serialize(void *, char *);
void tree_sitter_blade_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_blade(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_blade_external_scanner_create,
      tree_sitter_blade_external_scanner_destroy,
      tree_sitter_blade_external_scanner_scan,
      tree_sitter_blade_external_scanner_serialize,
      tree_sitter_blade_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
