#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 124
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 50
#define ALIAS_COUNT 0
#define TOKEN_COUNT 30
#define EXTERNAL_TOKEN_COUNT 15
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LT_BANG = 1,
  aux_sym_doctype_token1 = 2,
  anon_sym_GT = 3,
  sym__doctype = 4,
  anon_sym_LT = 5,
  anon_sym_SLASH_GT = 6,
  anon_sym_LT_SLASH = 7,
  anon_sym_EQ = 8,
  sym_attribute_name = 9,
  aux_sym_attribute_value_token1 = 10,
  sym_entity = 11,
  anon_sym_SQUOTE = 12,
  aux_sym_quoted_attribute_value_token1 = 13,
  anon_sym_DQUOTE = 14,
  aux_sym_quoted_attribute_value_token2 = 15,
  sym__escaped_echo_statement_start = 16,
  sym__escaped_echo_statement_end = 17,
  sym__unescaped_echo_statement_start = 18,
  sym__unescaped_echo_statement_end = 19,
  sym__start_tag_name = 20,
  sym__script_start_tag_name = 21,
  sym__style_start_tag_name = 22,
  sym__end_tag_name = 23,
  sym_erroneous_end_tag_name = 24,
  sym__implicit_end_tag = 25,
  sym_raw_text = 26,
  sym_text = 27,
  sym_comment = 28,
  sym_test = 29,
  sym_document = 30,
  sym_doctype = 31,
  sym_echo_statement = 32,
  sym_escaped_echo_statement = 33,
  sym_unescaped_echo_statement = 34,
  sym__node = 35,
  sym_element = 36,
  sym_script_element = 37,
  sym_style_element = 38,
  sym_start_tag = 39,
  sym_script_start_tag = 40,
  sym_style_start_tag = 41,
  sym_self_closing_tag = 42,
  sym_end_tag = 43,
  sym_erroneous_end_tag = 44,
  sym_attribute = 45,
  sym_attribute_value = 46,
  sym_quoted_attribute_value = 47,
  aux_sym_document_repeat1 = 48,
  aux_sym_start_tag_repeat1 = 49,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT_BANG] = "<!",
  [aux_sym_doctype_token1] = "doctype_token1",
  [anon_sym_GT] = ">",
  [sym__doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [aux_sym_attribute_value_token1] = "attribute_value_token1",
  [sym_entity] = "entity",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [sym__escaped_echo_statement_start] = "_escaped_echo_statement_start",
  [sym__escaped_echo_statement_end] = "_escaped_echo_statement_end",
  [sym__unescaped_echo_statement_start] = "_unescaped_echo_statement_start",
  [sym__unescaped_echo_statement_end] = "_unescaped_echo_statement_end",
  [sym__start_tag_name] = "tag_name",
  [sym__script_start_tag_name] = "tag_name",
  [sym__style_start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_erroneous_end_tag_name] = "erroneous_end_tag_name",
  [sym__implicit_end_tag] = "_implicit_end_tag",
  [sym_raw_text] = "raw_text",
  [sym_text] = "text",
  [sym_comment] = "comment",
  [sym_test] = "test",
  [sym_document] = "document",
  [sym_doctype] = "doctype",
  [sym_echo_statement] = "echo_statement",
  [sym_escaped_echo_statement] = "escaped_echo_statement",
  [sym_unescaped_echo_statement] = "unescaped_echo_statement",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_script_element] = "script_element",
  [sym_style_element] = "style_element",
  [sym_start_tag] = "start_tag",
  [sym_script_start_tag] = "start_tag",
  [sym_style_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_erroneous_end_tag] = "erroneous_end_tag",
  [sym_attribute] = "attribute",
  [sym_attribute_value] = "attribute_value",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT_BANG] = anon_sym_LT_BANG,
  [aux_sym_doctype_token1] = aux_sym_doctype_token1,
  [anon_sym_GT] = anon_sym_GT,
  [sym__doctype] = sym__doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [aux_sym_attribute_value_token1] = aux_sym_attribute_value_token1,
  [sym_entity] = sym_entity,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [sym__escaped_echo_statement_start] = sym__escaped_echo_statement_start,
  [sym__escaped_echo_statement_end] = sym__escaped_echo_statement_end,
  [sym__unescaped_echo_statement_start] = sym__unescaped_echo_statement_start,
  [sym__unescaped_echo_statement_end] = sym__unescaped_echo_statement_end,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__script_start_tag_name] = sym__start_tag_name,
  [sym__style_start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [sym__implicit_end_tag] = sym__implicit_end_tag,
  [sym_raw_text] = sym_raw_text,
  [sym_text] = sym_text,
  [sym_comment] = sym_comment,
  [sym_test] = sym_test,
  [sym_document] = sym_document,
  [sym_doctype] = sym_doctype,
  [sym_echo_statement] = sym_echo_statement,
  [sym_escaped_echo_statement] = sym_escaped_echo_statement,
  [sym_unescaped_echo_statement] = sym_unescaped_echo_statement,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_script_element] = sym_script_element,
  [sym_style_element] = sym_style_element,
  [sym_start_tag] = sym_start_tag,
  [sym_script_start_tag] = sym_start_tag,
  [sym_style_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_erroneous_end_tag] = sym_erroneous_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_attribute_value] = sym_attribute_value,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT_BANG] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_doctype_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym__doctype] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_attribute_value_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_entity] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym__escaped_echo_statement_start] = {
    .visible = false,
    .named = true,
  },
  [sym__escaped_echo_statement_end] = {
    .visible = false,
    .named = true,
  },
  [sym__unescaped_echo_statement_start] = {
    .visible = false,
    .named = true,
  },
  [sym__unescaped_echo_statement_end] = {
    .visible = false,
    .named = true,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__script_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__style_start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__implicit_end_tag] = {
    .visible = false,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_test] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [sym_echo_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_escaped_echo_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_unescaped_echo_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_script_element] = {
    .visible = true,
    .named = true,
  },
  [sym_style_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_script_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_style_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_erroneous_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 12,
  [14] = 10,
  [15] = 9,
  [16] = 11,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 21,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 36,
  [38] = 38,
  [39] = 33,
  [40] = 35,
  [41] = 34,
  [42] = 32,
  [43] = 31,
  [44] = 28,
  [45] = 22,
  [46] = 30,
  [47] = 29,
  [48] = 27,
  [49] = 49,
  [50] = 26,
  [51] = 25,
  [52] = 24,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 36,
  [58] = 35,
  [59] = 59,
  [60] = 53,
  [61] = 25,
  [62] = 59,
  [63] = 36,
  [64] = 35,
  [65] = 25,
  [66] = 55,
  [67] = 54,
  [68] = 56,
  [69] = 69,
  [70] = 69,
  [71] = 71,
  [72] = 72,
  [73] = 72,
  [74] = 71,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 78,
  [81] = 81,
  [82] = 81,
  [83] = 83,
  [84] = 75,
  [85] = 83,
  [86] = 86,
  [87] = 87,
  [88] = 79,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 90,
  [98] = 98,
  [99] = 99,
  [100] = 89,
  [101] = 101,
  [102] = 99,
  [103] = 103,
  [104] = 93,
  [105] = 94,
  [106] = 106,
  [107] = 92,
  [108] = 93,
  [109] = 94,
  [110] = 93,
  [111] = 94,
  [112] = 106,
  [113] = 103,
  [114] = 114,
  [115] = 95,
  [116] = 114,
  [117] = 96,
  [118] = 98,
  [119] = 106,
  [120] = 103,
  [121] = 106,
  [122] = 103,
  [123] = 101,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '"', 71,
        '&', 3,
        '\'', 68,
        '/', 6,
        '<', 22,
        '=', 25,
        '>', 20,
        'D', 9,
        'd', 9,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(71);
      if (lookahead == '\'') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(27);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(71);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(68);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(69);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '>') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(26);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(23);
      END_STATE();
    case 7:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(11);
      END_STATE();
    case 8:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(21);
      END_STATE();
    case 9:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 13:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(10);
      END_STATE();
    case 14:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_LT_BANG);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_doctype_token1);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym__doctype);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(17);
      if (lookahead == '/') ADVANCE(24);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_entity);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(29);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(34);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(36);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(29);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(28);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(70);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(73);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 3},
  [9] = {.lex_state = 5, .external_lex_state = 4},
  [10] = {.lex_state = 1, .external_lex_state = 5},
  [11] = {.lex_state = 5, .external_lex_state = 4},
  [12] = {.lex_state = 5, .external_lex_state = 4},
  [13] = {.lex_state = 5, .external_lex_state = 4},
  [14] = {.lex_state = 1, .external_lex_state = 5},
  [15] = {.lex_state = 5, .external_lex_state = 4},
  [16] = {.lex_state = 5, .external_lex_state = 5},
  [17] = {.lex_state = 5, .external_lex_state = 5},
  [18] = {.lex_state = 5, .external_lex_state = 5},
  [19] = {.lex_state = 5, .external_lex_state = 5},
  [20] = {.lex_state = 5, .external_lex_state = 5},
  [21] = {.lex_state = 0, .external_lex_state = 3},
  [22] = {.lex_state = 0, .external_lex_state = 3},
  [23] = {.lex_state = 0, .external_lex_state = 2},
  [24] = {.lex_state = 0, .external_lex_state = 3},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 3},
  [27] = {.lex_state = 0, .external_lex_state = 3},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0, .external_lex_state = 3},
  [30] = {.lex_state = 0, .external_lex_state = 3},
  [31] = {.lex_state = 0, .external_lex_state = 3},
  [32] = {.lex_state = 0, .external_lex_state = 2},
  [33] = {.lex_state = 0, .external_lex_state = 3},
  [34] = {.lex_state = 0, .external_lex_state = 2},
  [35] = {.lex_state = 0, .external_lex_state = 2},
  [36] = {.lex_state = 0, .external_lex_state = 2},
  [37] = {.lex_state = 0, .external_lex_state = 3},
  [38] = {.lex_state = 0, .external_lex_state = 3},
  [39] = {.lex_state = 0, .external_lex_state = 2},
  [40] = {.lex_state = 0, .external_lex_state = 3},
  [41] = {.lex_state = 0, .external_lex_state = 3},
  [42] = {.lex_state = 0, .external_lex_state = 3},
  [43] = {.lex_state = 0, .external_lex_state = 2},
  [44] = {.lex_state = 0, .external_lex_state = 3},
  [45] = {.lex_state = 0, .external_lex_state = 2},
  [46] = {.lex_state = 0, .external_lex_state = 2},
  [47] = {.lex_state = 0, .external_lex_state = 2},
  [48] = {.lex_state = 0, .external_lex_state = 2},
  [49] = {.lex_state = 0, .external_lex_state = 3},
  [50] = {.lex_state = 0, .external_lex_state = 2},
  [51] = {.lex_state = 0, .external_lex_state = 3},
  [52] = {.lex_state = 0, .external_lex_state = 2},
  [53] = {.lex_state = 5, .external_lex_state = 4},
  [54] = {.lex_state = 5, .external_lex_state = 4},
  [55] = {.lex_state = 5, .external_lex_state = 4},
  [56] = {.lex_state = 5, .external_lex_state = 4},
  [57] = {.lex_state = 5, .external_lex_state = 4},
  [58] = {.lex_state = 5, .external_lex_state = 4},
  [59] = {.lex_state = 5, .external_lex_state = 4},
  [60] = {.lex_state = 5, .external_lex_state = 5},
  [61] = {.lex_state = 5, .external_lex_state = 4},
  [62] = {.lex_state = 5, .external_lex_state = 5},
  [63] = {.lex_state = 5, .external_lex_state = 5},
  [64] = {.lex_state = 5, .external_lex_state = 5},
  [65] = {.lex_state = 5, .external_lex_state = 5},
  [66] = {.lex_state = 5, .external_lex_state = 5},
  [67] = {.lex_state = 5, .external_lex_state = 5},
  [68] = {.lex_state = 5, .external_lex_state = 5},
  [69] = {.lex_state = 0, .external_lex_state = 6},
  [70] = {.lex_state = 0, .external_lex_state = 6},
  [71] = {.lex_state = 0, .external_lex_state = 7},
  [72] = {.lex_state = 0, .external_lex_state = 7},
  [73] = {.lex_state = 0, .external_lex_state = 7},
  [74] = {.lex_state = 0, .external_lex_state = 7},
  [75] = {.lex_state = 0, .external_lex_state = 8},
  [76] = {.lex_state = 0, .external_lex_state = 7},
  [77] = {.lex_state = 0, .external_lex_state = 7},
  [78] = {.lex_state = 0, .external_lex_state = 9},
  [79] = {.lex_state = 0, .external_lex_state = 8},
  [80] = {.lex_state = 0, .external_lex_state = 9},
  [81] = {.lex_state = 2, .external_lex_state = 8},
  [82] = {.lex_state = 2, .external_lex_state = 8},
  [83] = {.lex_state = 4, .external_lex_state = 8},
  [84] = {.lex_state = 0, .external_lex_state = 8},
  [85] = {.lex_state = 4, .external_lex_state = 8},
  [86] = {.lex_state = 0, .external_lex_state = 7},
  [87] = {.lex_state = 0, .external_lex_state = 7},
  [88] = {.lex_state = 0, .external_lex_state = 8},
  [89] = {.lex_state = 0, .external_lex_state = 8},
  [90] = {.lex_state = 0, .external_lex_state = 8},
  [91] = {.lex_state = 0, .external_lex_state = 8},
  [92] = {.lex_state = 0, .external_lex_state = 8},
  [93] = {.lex_state = 0, .external_lex_state = 10},
  [94] = {.lex_state = 0, .external_lex_state = 11},
  [95] = {.lex_state = 0, .external_lex_state = 12},
  [96] = {.lex_state = 0, .external_lex_state = 8},
  [97] = {.lex_state = 0, .external_lex_state = 8},
  [98] = {.lex_state = 0, .external_lex_state = 13},
  [99] = {.lex_state = 0, .external_lex_state = 8},
  [100] = {.lex_state = 0, .external_lex_state = 8},
  [101] = {.lex_state = 0, .external_lex_state = 8},
  [102] = {.lex_state = 0, .external_lex_state = 8},
  [103] = {.lex_state = 0, .external_lex_state = 7},
  [104] = {.lex_state = 0, .external_lex_state = 10},
  [105] = {.lex_state = 0, .external_lex_state = 11},
  [106] = {.lex_state = 0, .external_lex_state = 7},
  [107] = {.lex_state = 0, .external_lex_state = 8},
  [108] = {.lex_state = 0, .external_lex_state = 10},
  [109] = {.lex_state = 0, .external_lex_state = 11},
  [110] = {.lex_state = 0, .external_lex_state = 10},
  [111] = {.lex_state = 0, .external_lex_state = 11},
  [112] = {.lex_state = 0, .external_lex_state = 7},
  [113] = {.lex_state = 0, .external_lex_state = 7},
  [114] = {.lex_state = 14, .external_lex_state = 8},
  [115] = {.lex_state = 0, .external_lex_state = 12},
  [116] = {.lex_state = 14, .external_lex_state = 8},
  [117] = {.lex_state = 0, .external_lex_state = 8},
  [118] = {.lex_state = 0, .external_lex_state = 13},
  [119] = {.lex_state = 0, .external_lex_state = 7},
  [120] = {.lex_state = 0, .external_lex_state = 7},
  [121] = {.lex_state = 0, .external_lex_state = 7},
  [122] = {.lex_state = 0, .external_lex_state = 7},
  [123] = {.lex_state = 0, .external_lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT_BANG] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym__doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_entity] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__escaped_echo_statement_start] = ACTIONS(1),
    [sym__escaped_echo_statement_end] = ACTIONS(1),
    [sym__unescaped_echo_statement_start] = ACTIONS(1),
    [sym__unescaped_echo_statement_end] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__script_start_tag_name] = ACTIONS(1),
    [sym__style_start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_erroneous_end_tag_name] = ACTIONS(1),
    [sym__implicit_end_tag] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_test] = ACTIONS(3),
  },
  [1] = {
    [sym_document] = STATE(91),
    [sym_doctype] = STATE(6),
    [sym_echo_statement] = STATE(6),
    [sym_escaped_echo_statement] = STATE(25),
    [sym_unescaped_echo_statement] = STATE(25),
    [sym__node] = STATE(6),
    [sym_element] = STATE(6),
    [sym_script_element] = STATE(6),
    [sym_style_element] = STATE(6),
    [sym_start_tag] = STATE(2),
    [sym_script_start_tag] = STATE(73),
    [sym_style_start_tag] = STATE(74),
    [sym_self_closing_tag] = STATE(23),
    [sym_erroneous_end_tag] = STATE(6),
    [aux_sym_document_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT_BANG] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(11),
    [sym_entity] = ACTIONS(13),
    [sym__escaped_echo_statement_start] = ACTIONS(15),
    [sym__unescaped_echo_statement_start] = ACTIONS(17),
    [sym_text] = ACTIONS(13),
    [sym_comment] = ACTIONS(3),
    [sym_test] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(23), 1,
      anon_sym_LT_SLASH,
    ACTIONS(27), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(29), 1,
      sym__unescaped_echo_statement_start,
    ACTIONS(31), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(28), 1,
      sym_end_tag,
    STATE(71), 1,
      sym_style_start_tag,
    STATE(72), 1,
      sym_script_start_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(25), 2,
      sym_text,
      sym_entity,
    STATE(51), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(3), 8,
      sym_doctype,
      sym_echo_statement,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [56] = 15,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(23), 1,
      anon_sym_LT_SLASH,
    ACTIONS(27), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(29), 1,
      sym__unescaped_echo_statement_start,
    ACTIONS(35), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(45), 1,
      sym_end_tag,
    STATE(71), 1,
      sym_style_start_tag,
    STATE(72), 1,
      sym_script_start_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(33), 2,
      sym_text,
      sym_entity,
    STATE(51), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(8), 8,
      sym_doctype,
      sym_echo_statement,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [112] = 15,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(29), 1,
      sym__unescaped_echo_statement_start,
    ACTIONS(37), 1,
      anon_sym_LT_SLASH,
    ACTIONS(39), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(22), 1,
      sym_end_tag,
    STATE(71), 1,
      sym_style_start_tag,
    STATE(72), 1,
      sym_script_start_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(33), 2,
      sym_text,
      sym_entity,
    STATE(51), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(8), 8,
      sym_doctype,
      sym_echo_statement,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [168] = 15,
    ACTIONS(19), 1,
      anon_sym_LT_BANG,
    ACTIONS(21), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(29), 1,
      sym__unescaped_echo_statement_start,
    ACTIONS(37), 1,
      anon_sym_LT_SLASH,
    ACTIONS(43), 1,
      sym__implicit_end_tag,
    STATE(5), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(44), 1,
      sym_end_tag,
    STATE(71), 1,
      sym_style_start_tag,
    STATE(72), 1,
      sym_script_start_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(41), 2,
      sym_text,
      sym_entity,
    STATE(51), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(4), 8,
      sym_doctype,
      sym_echo_statement,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [224] = 14,
    ACTIONS(7), 1,
      anon_sym_LT_BANG,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      anon_sym_LT_SLASH,
    ACTIONS(15), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(17), 1,
      sym__unescaped_echo_statement_start,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_start_tag,
    STATE(23), 1,
      sym_self_closing_tag,
    STATE(73), 1,
      sym_script_start_tag,
    STATE(74), 1,
      sym_style_start_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(47), 2,
      sym_text,
      sym_entity,
    STATE(25), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(7), 8,
      sym_doctype,
      sym_echo_statement,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [277] = 14,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      anon_sym_LT_BANG,
    ACTIONS(54), 1,
      anon_sym_LT,
    ACTIONS(57), 1,
      anon_sym_LT_SLASH,
    ACTIONS(63), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(66), 1,
      sym__unescaped_echo_statement_start,
    STATE(2), 1,
      sym_start_tag,
    STATE(23), 1,
      sym_self_closing_tag,
    STATE(73), 1,
      sym_script_start_tag,
    STATE(74), 1,
      sym_style_start_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(60), 2,
      sym_text,
      sym_entity,
    STATE(25), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(7), 8,
      sym_doctype,
      sym_echo_statement,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [330] = 14,
    ACTIONS(49), 1,
      sym__implicit_end_tag,
    ACTIONS(69), 1,
      anon_sym_LT_BANG,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(75), 1,
      anon_sym_LT_SLASH,
    ACTIONS(81), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(84), 1,
      sym__unescaped_echo_statement_start,
    STATE(5), 1,
      sym_start_tag,
    STATE(21), 1,
      sym_self_closing_tag,
    STATE(71), 1,
      sym_style_start_tag,
    STATE(72), 1,
      sym_script_start_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(78), 2,
      sym_text,
      sym_entity,
    STATE(51), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(8), 8,
      sym_doctype,
      sym_echo_statement,
      sym__node,
      sym_element,
      sym_script_element,
      sym_style_element,
      sym_erroneous_end_tag,
      aux_sym_document_repeat1,
  [383] = 8,
    ACTIONS(87), 1,
      anon_sym_GT,
    ACTIONS(89), 1,
      anon_sym_SLASH_GT,
    ACTIONS(91), 1,
      sym_attribute_name,
    ACTIONS(93), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(95), 1,
      sym__unescaped_echo_statement_start,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    STATE(61), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(12), 3,
      sym_echo_statement,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [412] = 9,
    ACTIONS(97), 1,
      aux_sym_attribute_value_token1,
    ACTIONS(99), 1,
      anon_sym_SQUOTE,
    ACTIONS(101), 1,
      anon_sym_DQUOTE,
    ACTIONS(103), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(105), 1,
      sym__unescaped_echo_statement_start,
    STATE(62), 1,
      sym_echo_statement,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    STATE(65), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(66), 2,
      sym_attribute_value,
      sym_quoted_attribute_value,
  [443] = 7,
    ACTIONS(109), 1,
      sym_attribute_name,
    ACTIONS(112), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(115), 1,
      sym__unescaped_echo_statement_start,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(107), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(61), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(11), 3,
      sym_echo_statement,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [470] = 8,
    ACTIONS(91), 1,
      sym_attribute_name,
    ACTIONS(93), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(95), 1,
      sym__unescaped_echo_statement_start,
    ACTIONS(118), 1,
      anon_sym_GT,
    ACTIONS(120), 1,
      anon_sym_SLASH_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    STATE(61), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(11), 3,
      sym_echo_statement,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [499] = 8,
    ACTIONS(91), 1,
      sym_attribute_name,
    ACTIONS(93), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(95), 1,
      sym__unescaped_echo_statement_start,
    ACTIONS(118), 1,
      anon_sym_GT,
    ACTIONS(122), 1,
      anon_sym_SLASH_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    STATE(61), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(11), 3,
      sym_echo_statement,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [528] = 9,
    ACTIONS(93), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(95), 1,
      sym__unescaped_echo_statement_start,
    ACTIONS(124), 1,
      aux_sym_attribute_value_token1,
    ACTIONS(126), 1,
      anon_sym_SQUOTE,
    ACTIONS(128), 1,
      anon_sym_DQUOTE,
    STATE(59), 1,
      sym_echo_statement,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    STATE(55), 2,
      sym_attribute_value,
      sym_quoted_attribute_value,
    STATE(61), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
  [559] = 8,
    ACTIONS(87), 1,
      anon_sym_GT,
    ACTIONS(91), 1,
      sym_attribute_name,
    ACTIONS(93), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(95), 1,
      sym__unescaped_echo_statement_start,
    ACTIONS(130), 1,
      anon_sym_SLASH_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    STATE(61), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(13), 3,
      sym_echo_statement,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [588] = 7,
    ACTIONS(107), 1,
      anon_sym_GT,
    ACTIONS(132), 1,
      sym_attribute_name,
    ACTIONS(135), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(138), 1,
      sym__unescaped_echo_statement_start,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    STATE(65), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(16), 3,
      sym_echo_statement,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [614] = 7,
    ACTIONS(103), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(105), 1,
      sym__unescaped_echo_statement_start,
    ACTIONS(141), 1,
      anon_sym_GT,
    ACTIONS(143), 1,
      sym_attribute_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    STATE(65), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(16), 3,
      sym_echo_statement,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [640] = 7,
    ACTIONS(103), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(105), 1,
      sym__unescaped_echo_statement_start,
    ACTIONS(143), 1,
      sym_attribute_name,
    ACTIONS(145), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    STATE(65), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(20), 3,
      sym_echo_statement,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [666] = 7,
    ACTIONS(103), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(105), 1,
      sym__unescaped_echo_statement_start,
    ACTIONS(143), 1,
      sym_attribute_name,
    ACTIONS(147), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    STATE(65), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(17), 3,
      sym_echo_statement,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [692] = 7,
    ACTIONS(103), 1,
      sym__escaped_echo_statement_start,
    ACTIONS(105), 1,
      sym__unescaped_echo_statement_start,
    ACTIONS(143), 1,
      sym_attribute_name,
    ACTIONS(149), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    STATE(65), 2,
      sym_escaped_echo_statement,
      sym_unescaped_echo_statement,
    STATE(16), 3,
      sym_echo_statement,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [718] = 3,
    ACTIONS(153), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(151), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [735] = 3,
    ACTIONS(157), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(155), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [752] = 3,
    ACTIONS(153), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(151), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [769] = 3,
    ACTIONS(161), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(159), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [786] = 3,
    ACTIONS(165), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(163), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [803] = 3,
    ACTIONS(169), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(167), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [820] = 3,
    ACTIONS(173), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(171), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [837] = 3,
    ACTIONS(177), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(175), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [854] = 3,
    ACTIONS(181), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(179), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [871] = 3,
    ACTIONS(185), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(183), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [888] = 3,
    ACTIONS(189), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(187), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [905] = 3,
    ACTIONS(193), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(191), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [922] = 3,
    ACTIONS(197), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(195), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [939] = 3,
    ACTIONS(201), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(199), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [956] = 3,
    ACTIONS(205), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(203), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [973] = 3,
    ACTIONS(209), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(207), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [990] = 3,
    ACTIONS(209), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(207), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [1007] = 3,
    ACTIONS(213), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(211), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [1024] = 3,
    ACTIONS(197), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(195), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [1041] = 3,
    ACTIONS(205), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(203), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [1058] = 3,
    ACTIONS(201), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(199), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [1075] = 3,
    ACTIONS(193), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(191), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [1092] = 3,
    ACTIONS(189), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(187), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [1109] = 3,
    ACTIONS(177), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(175), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [1126] = 3,
    ACTIONS(157), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(155), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [1143] = 3,
    ACTIONS(185), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(183), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [1160] = 3,
    ACTIONS(181), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(179), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [1177] = 3,
    ACTIONS(173), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(171), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [1194] = 3,
    ACTIONS(217), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(215), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [1211] = 3,
    ACTIONS(169), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(167), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [1228] = 3,
    ACTIONS(165), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(163), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym__implicit_end_tag,
      sym_text,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [1245] = 3,
    ACTIONS(161), 1,
      anon_sym_LT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(159), 7,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_LT_BANG,
      anon_sym_LT_SLASH,
      sym_entity,
  [1262] = 3,
    ACTIONS(221), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(219), 5,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1277] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(223), 5,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1289] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(225), 5,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1301] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(227), 5,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1313] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(207), 5,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1325] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(203), 5,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1337] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(229), 5,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1349] = 3,
    ACTIONS(231), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(219), 4,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      anon_sym_GT,
      sym_attribute_name,
  [1363] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(163), 5,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1375] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(229), 4,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      anon_sym_GT,
      sym_attribute_name,
  [1386] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(207), 4,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      anon_sym_GT,
      sym_attribute_name,
  [1397] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(203), 4,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      anon_sym_GT,
      sym_attribute_name,
  [1408] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(163), 4,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      anon_sym_GT,
      sym_attribute_name,
  [1419] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(225), 4,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      anon_sym_GT,
      sym_attribute_name,
  [1430] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(223), 4,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      anon_sym_GT,
      sym_attribute_name,
  [1441] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(227), 4,
      sym__escaped_echo_statement_start,
      sym__unescaped_echo_statement_start,
      anon_sym_GT,
      sym_attribute_name,
  [1452] = 4,
    ACTIONS(233), 1,
      sym__start_tag_name,
    ACTIONS(235), 1,
      sym__script_start_tag_name,
    ACTIONS(237), 1,
      sym__style_start_tag_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1466] = 4,
    ACTIONS(235), 1,
      sym__script_start_tag_name,
    ACTIONS(237), 1,
      sym__style_start_tag_name,
    ACTIONS(239), 1,
      sym__start_tag_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1480] = 4,
    ACTIONS(241), 1,
      anon_sym_LT_SLASH,
    ACTIONS(243), 1,
      sym_raw_text,
    STATE(41), 1,
      sym_end_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1494] = 4,
    ACTIONS(241), 1,
      anon_sym_LT_SLASH,
    ACTIONS(245), 1,
      sym_raw_text,
    STATE(42), 1,
      sym_end_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1508] = 4,
    ACTIONS(247), 1,
      anon_sym_LT_SLASH,
    ACTIONS(249), 1,
      sym_raw_text,
    STATE(32), 1,
      sym_end_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1522] = 4,
    ACTIONS(247), 1,
      anon_sym_LT_SLASH,
    ACTIONS(251), 1,
      sym_raw_text,
    STATE(34), 1,
      sym_end_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1536] = 3,
    ACTIONS(247), 1,
      anon_sym_LT_SLASH,
    STATE(47), 1,
      sym_end_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1547] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(253), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1556] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(255), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1565] = 3,
    ACTIONS(257), 1,
      sym__end_tag_name,
    ACTIONS(259), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1576] = 3,
    ACTIONS(247), 1,
      anon_sym_LT_SLASH,
    STATE(46), 1,
      sym_end_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1587] = 3,
    ACTIONS(259), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(261), 1,
      sym__end_tag_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1598] = 3,
    ACTIONS(263), 1,
      anon_sym_DQUOTE,
    ACTIONS(265), 1,
      aux_sym_quoted_attribute_value_token2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1609] = 3,
    ACTIONS(267), 1,
      anon_sym_DQUOTE,
    ACTIONS(269), 1,
      aux_sym_quoted_attribute_value_token2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1620] = 3,
    ACTIONS(267), 1,
      anon_sym_SQUOTE,
    ACTIONS(271), 1,
      aux_sym_quoted_attribute_value_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1631] = 3,
    ACTIONS(241), 1,
      anon_sym_LT_SLASH,
    STATE(29), 1,
      sym_end_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1642] = 3,
    ACTIONS(263), 1,
      anon_sym_SQUOTE,
    ACTIONS(273), 1,
      aux_sym_quoted_attribute_value_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1653] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(275), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1662] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
    ACTIONS(277), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1671] = 3,
    ACTIONS(241), 1,
      anon_sym_LT_SLASH,
    STATE(30), 1,
      sym_end_tag,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1682] = 2,
    ACTIONS(279), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1690] = 2,
    ACTIONS(281), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1698] = 2,
    ACTIONS(283), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1706] = 2,
    ACTIONS(285), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1714] = 2,
    ACTIONS(287), 1,
      sym__escaped_echo_statement_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1722] = 2,
    ACTIONS(289), 1,
      sym__unescaped_echo_statement_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1730] = 2,
    ACTIONS(291), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1738] = 2,
    ACTIONS(293), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1746] = 2,
    ACTIONS(285), 1,
      anon_sym_SQUOTE,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1754] = 2,
    ACTIONS(261), 1,
      sym__end_tag_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1762] = 2,
    ACTIONS(295), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1770] = 2,
    ACTIONS(297), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1778] = 2,
    ACTIONS(299), 1,
      sym__doctype,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1786] = 2,
    ACTIONS(301), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1794] = 2,
    ACTIONS(303), 1,
      sym_raw_text,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1802] = 2,
    ACTIONS(305), 1,
      sym__escaped_echo_statement_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1810] = 2,
    ACTIONS(307), 1,
      sym__unescaped_echo_statement_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1818] = 2,
    ACTIONS(309), 1,
      sym_raw_text,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1826] = 2,
    ACTIONS(281), 1,
      anon_sym_DQUOTE,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1834] = 2,
    ACTIONS(311), 1,
      sym__escaped_echo_statement_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1842] = 2,
    ACTIONS(313), 1,
      sym__unescaped_echo_statement_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1850] = 2,
    ACTIONS(315), 1,
      sym__escaped_echo_statement_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1858] = 2,
    ACTIONS(317), 1,
      sym__unescaped_echo_statement_end,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1866] = 2,
    ACTIONS(319), 1,
      sym_raw_text,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1874] = 2,
    ACTIONS(321), 1,
      sym_raw_text,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1882] = 2,
    ACTIONS(323), 1,
      aux_sym_doctype_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1890] = 2,
    ACTIONS(259), 1,
      sym_erroneous_end_tag_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1898] = 2,
    ACTIONS(325), 1,
      aux_sym_doctype_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1906] = 2,
    ACTIONS(327), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1914] = 2,
    ACTIONS(257), 1,
      sym__end_tag_name,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1922] = 2,
    ACTIONS(329), 1,
      sym_raw_text,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1930] = 2,
    ACTIONS(331), 1,
      sym_raw_text,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1938] = 2,
    ACTIONS(333), 1,
      sym_raw_text,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1946] = 2,
    ACTIONS(335), 1,
      sym_raw_text,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
  [1954] = 2,
    ACTIONS(337), 1,
      sym__doctype,
    ACTIONS(3), 2,
      sym_comment,
      sym_test,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 56,
  [SMALL_STATE(4)] = 112,
  [SMALL_STATE(5)] = 168,
  [SMALL_STATE(6)] = 224,
  [SMALL_STATE(7)] = 277,
  [SMALL_STATE(8)] = 330,
  [SMALL_STATE(9)] = 383,
  [SMALL_STATE(10)] = 412,
  [SMALL_STATE(11)] = 443,
  [SMALL_STATE(12)] = 470,
  [SMALL_STATE(13)] = 499,
  [SMALL_STATE(14)] = 528,
  [SMALL_STATE(15)] = 559,
  [SMALL_STATE(16)] = 588,
  [SMALL_STATE(17)] = 614,
  [SMALL_STATE(18)] = 640,
  [SMALL_STATE(19)] = 666,
  [SMALL_STATE(20)] = 692,
  [SMALL_STATE(21)] = 718,
  [SMALL_STATE(22)] = 735,
  [SMALL_STATE(23)] = 752,
  [SMALL_STATE(24)] = 769,
  [SMALL_STATE(25)] = 786,
  [SMALL_STATE(26)] = 803,
  [SMALL_STATE(27)] = 820,
  [SMALL_STATE(28)] = 837,
  [SMALL_STATE(29)] = 854,
  [SMALL_STATE(30)] = 871,
  [SMALL_STATE(31)] = 888,
  [SMALL_STATE(32)] = 905,
  [SMALL_STATE(33)] = 922,
  [SMALL_STATE(34)] = 939,
  [SMALL_STATE(35)] = 956,
  [SMALL_STATE(36)] = 973,
  [SMALL_STATE(37)] = 990,
  [SMALL_STATE(38)] = 1007,
  [SMALL_STATE(39)] = 1024,
  [SMALL_STATE(40)] = 1041,
  [SMALL_STATE(41)] = 1058,
  [SMALL_STATE(42)] = 1075,
  [SMALL_STATE(43)] = 1092,
  [SMALL_STATE(44)] = 1109,
  [SMALL_STATE(45)] = 1126,
  [SMALL_STATE(46)] = 1143,
  [SMALL_STATE(47)] = 1160,
  [SMALL_STATE(48)] = 1177,
  [SMALL_STATE(49)] = 1194,
  [SMALL_STATE(50)] = 1211,
  [SMALL_STATE(51)] = 1228,
  [SMALL_STATE(52)] = 1245,
  [SMALL_STATE(53)] = 1262,
  [SMALL_STATE(54)] = 1277,
  [SMALL_STATE(55)] = 1289,
  [SMALL_STATE(56)] = 1301,
  [SMALL_STATE(57)] = 1313,
  [SMALL_STATE(58)] = 1325,
  [SMALL_STATE(59)] = 1337,
  [SMALL_STATE(60)] = 1349,
  [SMALL_STATE(61)] = 1363,
  [SMALL_STATE(62)] = 1375,
  [SMALL_STATE(63)] = 1386,
  [SMALL_STATE(64)] = 1397,
  [SMALL_STATE(65)] = 1408,
  [SMALL_STATE(66)] = 1419,
  [SMALL_STATE(67)] = 1430,
  [SMALL_STATE(68)] = 1441,
  [SMALL_STATE(69)] = 1452,
  [SMALL_STATE(70)] = 1466,
  [SMALL_STATE(71)] = 1480,
  [SMALL_STATE(72)] = 1494,
  [SMALL_STATE(73)] = 1508,
  [SMALL_STATE(74)] = 1522,
  [SMALL_STATE(75)] = 1536,
  [SMALL_STATE(76)] = 1547,
  [SMALL_STATE(77)] = 1556,
  [SMALL_STATE(78)] = 1565,
  [SMALL_STATE(79)] = 1576,
  [SMALL_STATE(80)] = 1587,
  [SMALL_STATE(81)] = 1598,
  [SMALL_STATE(82)] = 1609,
  [SMALL_STATE(83)] = 1620,
  [SMALL_STATE(84)] = 1631,
  [SMALL_STATE(85)] = 1642,
  [SMALL_STATE(86)] = 1653,
  [SMALL_STATE(87)] = 1662,
  [SMALL_STATE(88)] = 1671,
  [SMALL_STATE(89)] = 1682,
  [SMALL_STATE(90)] = 1690,
  [SMALL_STATE(91)] = 1698,
  [SMALL_STATE(92)] = 1706,
  [SMALL_STATE(93)] = 1714,
  [SMALL_STATE(94)] = 1722,
  [SMALL_STATE(95)] = 1730,
  [SMALL_STATE(96)] = 1738,
  [SMALL_STATE(97)] = 1746,
  [SMALL_STATE(98)] = 1754,
  [SMALL_STATE(99)] = 1762,
  [SMALL_STATE(100)] = 1770,
  [SMALL_STATE(101)] = 1778,
  [SMALL_STATE(102)] = 1786,
  [SMALL_STATE(103)] = 1794,
  [SMALL_STATE(104)] = 1802,
  [SMALL_STATE(105)] = 1810,
  [SMALL_STATE(106)] = 1818,
  [SMALL_STATE(107)] = 1826,
  [SMALL_STATE(108)] = 1834,
  [SMALL_STATE(109)] = 1842,
  [SMALL_STATE(110)] = 1850,
  [SMALL_STATE(111)] = 1858,
  [SMALL_STATE(112)] = 1866,
  [SMALL_STATE(113)] = 1874,
  [SMALL_STATE(114)] = 1882,
  [SMALL_STATE(115)] = 1890,
  [SMALL_STATE(116)] = 1898,
  [SMALL_STATE(117)] = 1906,
  [SMALL_STATE(118)] = 1914,
  [SMALL_STATE(119)] = 1922,
  [SMALL_STATE(120)] = 1930,
  [SMALL_STATE(121)] = 1938,
  [SMALL_STATE(122)] = 1946,
  [SMALL_STATE(123)] = 1954,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(101),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(106),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(123),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(115),
  [78] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(112),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(113),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(119),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(120),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(121),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(122),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_echo_statement, 1, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_echo_statement, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_doctype, 4, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_doctype, 4, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 3, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_erroneous_end_tag, 3, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_erroneous_end_tag, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_element, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_script_element, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_element, 2, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_style_element, 2, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escaped_echo_statement, 3, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_escaped_echo_statement, 3, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unescaped_echo_statement, 3, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unescaped_echo_statement, 3, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 1, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 4, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 4, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [267] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_script_start_tag, 3, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_style_start_tag, 3, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [283] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__escaped_echo_statement_start = 0,
  ts_external_token__escaped_echo_statement_end = 1,
  ts_external_token__unescaped_echo_statement_start = 2,
  ts_external_token__unescaped_echo_statement_end = 3,
  ts_external_token__start_tag_name = 4,
  ts_external_token__script_start_tag_name = 5,
  ts_external_token__style_start_tag_name = 6,
  ts_external_token__end_tag_name = 7,
  ts_external_token_erroneous_end_tag_name = 8,
  ts_external_token_SLASH_GT = 9,
  ts_external_token__implicit_end_tag = 10,
  ts_external_token_raw_text = 11,
  ts_external_token_text = 12,
  ts_external_token_comment = 13,
  ts_external_token_test = 14,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__escaped_echo_statement_start] = sym__escaped_echo_statement_start,
  [ts_external_token__escaped_echo_statement_end] = sym__escaped_echo_statement_end,
  [ts_external_token__unescaped_echo_statement_start] = sym__unescaped_echo_statement_start,
  [ts_external_token__unescaped_echo_statement_end] = sym__unescaped_echo_statement_end,
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__script_start_tag_name] = sym__script_start_tag_name,
  [ts_external_token__style_start_tag_name] = sym__style_start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_erroneous_end_tag_name] = sym_erroneous_end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token__implicit_end_tag] = sym__implicit_end_tag,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_text] = sym_text,
  [ts_external_token_comment] = sym_comment,
  [ts_external_token_test] = sym_test,
};

static const bool ts_external_scanner_states[14][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__escaped_echo_statement_start] = true,
    [ts_external_token__escaped_echo_statement_end] = true,
    [ts_external_token__unescaped_echo_statement_start] = true,
    [ts_external_token__unescaped_echo_statement_end] = true,
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_text] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_test] = true,
  },
  [2] = {
    [ts_external_token__escaped_echo_statement_start] = true,
    [ts_external_token__unescaped_echo_statement_start] = true,
    [ts_external_token_text] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_test] = true,
  },
  [3] = {
    [ts_external_token__escaped_echo_statement_start] = true,
    [ts_external_token__unescaped_echo_statement_start] = true,
    [ts_external_token__implicit_end_tag] = true,
    [ts_external_token_text] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_test] = true,
  },
  [4] = {
    [ts_external_token__escaped_echo_statement_start] = true,
    [ts_external_token__unescaped_echo_statement_start] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_test] = true,
  },
  [5] = {
    [ts_external_token__escaped_echo_statement_start] = true,
    [ts_external_token__unescaped_echo_statement_start] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_test] = true,
  },
  [6] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__script_start_tag_name] = true,
    [ts_external_token__style_start_tag_name] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_test] = true,
  },
  [7] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_test] = true,
  },
  [8] = {
    [ts_external_token_comment] = true,
    [ts_external_token_test] = true,
  },
  [9] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_test] = true,
  },
  [10] = {
    [ts_external_token__escaped_echo_statement_end] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_test] = true,
  },
  [11] = {
    [ts_external_token__unescaped_echo_statement_end] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_test] = true,
  },
  [12] = {
    [ts_external_token_erroneous_end_tag_name] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_test] = true,
  },
  [13] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_comment] = true,
    [ts_external_token_test] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_blade_external_scanner_create(void);
void tree_sitter_blade_external_scanner_destroy(void *);
bool tree_sitter_blade_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_blade_external_scanner_serialize(void *, char *);
void tree_sitter_blade_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_blade(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_blade_external_scanner_create,
      tree_sitter_blade_external_scanner_destroy,
      tree_sitter_blade_external_scanner_scan,
      tree_sitter_blade_external_scanner_serialize,
      tree_sitter_blade_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
